runtime: custom
env: flex

automatic_scaling:
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.65
  min_instances: 1
  max_instances: 3

manual_scaling:
  instances: 1

env_variables:
  PORT: 8080
